# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"


  config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration s
  
  config.vm.provider "virtualbox" do |vb|
  
  vb.gui = true
  vb.name = "M300_Webserver"
  
  vb.memory = "4096"
  end
  
  #Werbserver
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y apache2



  #Firewall Rules
  sudo apt install ufw
  sudo ufw default deny incoming
  sudo ufw default allow outcoi
  sudo ufw allow ssh
  sudo ufw allow 80
  sudo ufw allow 8080
  sudo ufw allow 'Apache'
  sudo ufw --force enable
  sudo ufw --force status verbose
  SHELL
end
