# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # Provider-specific configuration s
  config.vm.synced_folder ".", "/var/www/html" 
config.vm.provider "virtualbox" do |vb|
  #vb.name = "M300_Webserver_Levin"
  vb.memory = "4096"
  end
  
  #Werbserver
  config.vm.provision "file", source: "../Website/index.php", destination: "/var/www/html/index.php"
  config.vm.provision "file", source: "../Website/.htpasswd", destination: "/var/www/html/.htpasswd"
  config.vm.provision "file", source: "../Website/.htaccess", destination: "/var/www/html/.htaccess"
  config.vm.provision "file", source: "../Website/apache2.conf", destination: "/var/www/html/apache2.conf"
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y apache2
  sudo apt -y install apache2 php libapache2-mod-php
  sudo apt-get update
  sudo apt-get install libcap2-bin wireshark
  sudo apt-get update
  sudo apt install software-properties-common
  sudo add-apt-repository ppa:deadsnakes/ppa
  sudo apt-get update
  sudo apt install python3.8
  
  #Firewall Rules
  sudo apt install ufw
  sudo ufw default deny incoming
  sudo ufw default allow outgoing
  sudo ufw allow ssh
  sudo ufw allow 80
  sudo ufw allow 8080
  sudo ufw allow 'Apache'
  sudo ufw --force enable
  sudo ufw --force status verbose
  
  SHELL
end
